In [1]:
import numpy as np

In [2]:
def encrypt(s,key):
        n = list()
        for i in s:
                n.append(ord(i))
        x = np.array(n)-97
        x = x.reshape(len(s),1)
        n1 = list()
        for i in key:
                n1.append(ord(i))
        k = np.array(n1)-97
        k = k.reshape(len(s),len(s))
        print(x)
        print(k)
        res = k.dot(x)%26
        res = res.reshape(1,len(s))
        res = res.tolist()
        result = ''
        for i in res[0]:
                result = result + chr(i+97)
        return result

In [3]:
s = input("Enter message: ")
k = input("Enter key: ")
print('Encrypted message: ' + encrypt(s,k))

Enter message: act
Enter key: baaabaaab
[[ 0]
 [ 2]
 [19]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Encrypted message: act
